import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import Main from '../components/Main'
import About from '../components/About'
import Skills from '../components/Skills'
import Projects from '../components/Projects'
import Interests1 from '../components/Interests1'
import Interests2 from '../components/Interests2'
import Contact from '../components/Contact'

import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() { 
  return (
    <div>
    <Head>
      <title>Anushka Kulkarni | Software Developer</title>
      <meta name = "description" content="generated by create next app" />
      <link rel="icon" href="/favicon.ico"/>
    </Head>
    <Navbar />
    <Main />
    <About />
    <Skills />
    <Projects />
    <Interests1 />
    <Interests2 />
    <Contact />
    </div>
  )
}

   