import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import Main from '../components/Main'
import About from '../components/About'
import Skills from '../components/Skills'
import Interests from '../components/Interests'

import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() { 
  return (
    <div>
    <Head>
      <title>Anushka Kulkarni | Software Developer</title>
      <meta name = "description" content="generated by create next app" />
      <link rel="icon" href="/favicon.ico"/>
    </Head>
    <Navbar />
    <Main />
    <About />
    <Skills />
    <Interests />

    </div>
  )
}

   